#!/usr/bin/env bash
SESSION_NAME="$1"
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RENAME_SCRIPT="$CURRENT_DIR/tmux-rename-session"
SWITCHER_SCRIPT="$CURRENT_DIR/sesh-switcher"

tmux display-popup -C
sleep 0.05
tmux display-popup -E -b none -x C -y 8 -w 50 -h 4 "bash \"$RENAME_SCRIPT\" \"$SESSION_NAME\" 50; tmux run-shell -b \"bash '$SWITCHER_SCRIPT'\""
