#!/usr/bin/env bash

if ! command -v fzf >/dev/null 2>&1; then
    tmux display-message "Error: fzf not found."
    exit 1
fi

get_tmux_option() {
    local val=$(tmux show-option -gqv "$1")
    [ -n "$val" ] && echo "$val" || echo "$2"
}

accent_color=$(get_tmux_option "@tmux-simple-renamers-accent" "#cba6f7")
secondary_color=$(get_tmux_option "@tmux-simple-renamers-secondary" "#7dc4e4")
text_color=$(get_tmux_option "@tmux-simple-renamers-text" "#cdd6f4")
bg_highlight=$(get_tmux_option "@tmux-simple-renamers-bg-highlight" "#313244")
gray_color=$(get_tmux_option "@tmux-simple-renamers-gray" "#6c7086")

current_idx=$(tmux display-message -p '#I')
all_wins=$(tmux list-windows -F '#I #W')
current_win=$(echo "$all_wins" | grep "^$current_idx ")
other_wins=$(echo "$all_wins" | grep -v "^$current_idx ")

cols=$(tput cols)
if [ "$cols" -gt 60 ]; then
  margin="--margin=30%,35%"
else
  margin=""
fi

{
  echo "$current_win"
  echo "$other_wins"
} | sed '/^$/d' | sed 's/^\([0-9]*\) \(.*\)$/󰖲 \1  󰈚 \2/' | fzf \
  --height=100% \
  --layout=reverse \
  --border=rounded \
  --border-label="󰑕 RENAME WINDOWS" \
  --border-label-pos=2 \
  --phony \
  --padding=0 \
  $margin \
  --bind 'ctrl-j:down,ctrl-k:up,ctrl-w:abort' \
  --bind 'enter:execute(tmux rename-window -t $(echo {} | grep -o "[0-9]\+") {q})+clear-query+reload(tmux list-windows -F "#I #W" | sed "/^$/d" | sed "s/^\([0-9]*\) \(.*\)$/󰖲 \1  󰈚 \2/")' \
  --color="bg:-1,bg+:$bg_highlight,fg:$text_color,fg+:$text_color,border:$accent_color,label:$accent_color,header:$gray_color,prompt:$secondary_color,pointer:$accent_color,marker:$accent_color,spinner:$text_color,info:$accent_color" \
  --prompt="󰊠  " \
  --pointer="▶" \
  --no-separator \
  --no-scrollbar \
  --info=hidden || true
